# Generated by Django 5.2.7 on 2025-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(default='PENDIENTE', max_length=200),
        ),
    ]
