# Generated by Django 5.2.7 on 2025-10-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_sku_alter_proveedor_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombre',
        ),
    ]
