# Generated by Django 5.2.7 on 2025-10-17 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_nombre_categoria_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='nombre_bodega',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
